const { test, expect } = require("@playwright/test");

test("approval queue renders the structured proposal dossier", async ({ page }) => {
  const entryName = `playwright-greenlight-${Date.now()}`;
  let approvalId;

  const response = await page.request.post("/mcp", {
    data: {
      jsonrpc: "2.0",
      id: "propose",
      method: "tools/call",
      params: {
        name: "argos_propose",
        arguments: {
          kind: "canon_update",
          body: {
            action: "add_entry",
            binding:
              "Execute the agreed scope straight through and surface results after, not before.",
            confidence: "test-confirmed",
            initialFailureModes: [
              {
                name: "permission-re-litigation",
                trigger:
                  "treating the go-signal as an invitation to ask more clarifying questions instead of executing"
              },
              {
                name: "scope-inflation",
                trigger:
                  "reading the energy of the signal as license to expand scope beyond what was actually agreed before the go"
              }
            ],
            name: entryName,
            observation: "A repeatable Playwright proposal for UI verification.",
            practice: "patterns",
            provenance: "Generated by the Playwright approval queue smoke test.",
            target: "constellation"
          }
        }
      }
    }
  });

  const payload = await response.json();
  approvalId = payload.result.structuredContent.proposal.approval_id;

  try {
    await page.goto("/approvals");

    const card = page
      .locator("article")
      .filter({ has: page.getByRole("heading", { name: entryName }) });

    await expect(page.getByRole("heading", { name: "Approval queue" })).toBeVisible();
    await expect(card.getByRole("heading", { name: entryName })).toBeVisible();
    await expect(card.getByRole("heading", { name: "Observation" })).toBeVisible();
    await expect(card.getByRole("heading", { name: "Binding" })).toBeVisible();
    await expect(card.getByRole("heading", { name: "Provenance" })).toBeVisible();
    await expect(card.getByRole("heading", { name: "Initial failure modes" })).toBeVisible();
    await expect(card.locator("p", { hasText: "permission-re-litigation" }).first()).toBeVisible();
    await expect(card.locator("p", { hasText: "scope-inflation" }).first()).toBeVisible();
    await expect(card.getByRole("button", { name: "Approve" })).toBeVisible();
    await expect(card.getByRole("button", { name: "Reject" })).toBeVisible();
  } finally {
    if (approvalId) {
      await page.request.post(`/api/approvals/${approvalId}/reject`, {
        data: { decided_by: "operator" }
      });
    }
  }
});
