defmodule Argos.Ingest.CrawlJobs do
  @moduledoc """
  Stores local crawl prompt packets and validated normalized ingest results.
  """

  import Ecto.Query

  alias Argos.Ingest.CrawlJob
  alias Argos.Kernel.Hashing
  alias Argos.Memory.Events
  alias Argos.Repo

  @schema_version "crawl_job_v1"

  def create_crawl(attrs) when is_map(attrs) do
    seek = map_value(attrs, "seek") || %{}
    raw_input = raw_input(attrs, seek)

    %CrawlJob{}
    |> CrawlJob.changeset(%{
      kind: "crawl",
      status: "queued",
      seek: seek,
      prompt: prompt(attrs, seek),
      raw_input: raw_input,
      raw_output: %{},
      normalized_records: %{
        "schema_version" => @schema_version,
        "records" => []
      },
      requested_at: DateTime.utc_now()
    })
    |> Repo.insert()
  end

  def crawl_and_ingest(attrs) when is_map(attrs) do
    seek = map_value(attrs, "seek") || %{}
    raw_output = map_value(attrs, "raw_output") || %{}

    with {:ok, normalized_records} <- normalize_records(attrs, raw_output) do
      Repo.transaction(fn ->
        with {:ok, job} <-
               insert_completed_job(attrs, seek, raw_output, normalized_records),
             {:ok, event} <- append_ingest_event(attrs, job, normalized_records),
             {:ok, job} <- set_event(job, event) do
          %{job: job, event: event}
        else
          {:error, reason} -> Repo.rollback(reason)
        end
      end)
      |> case do
        {:ok, result} -> {:ok, result}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  def list_jobs(opts \\ []) do
    CrawlJob
    |> maybe_filter_status(Keyword.get(opts, :status))
    |> order_by([job], desc: job.requested_at, desc: job.id)
    |> maybe_limit(Keyword.get(opts, :limit))
    |> Repo.all()
  end

  def get_job(id) when is_binary(id), do: Repo.get(CrawlJob, id)

  def output_schema do
    %{
      "type" => "object",
      "required" => ["records"],
      "properties" => %{
        "records" => %{
          "type" => "array",
          "items" => %{
            "type" => "object",
            "description" => "Domain record discovered or generated by the local AI runner."
          }
        }
      }
    }
  end

  defp insert_completed_job(attrs, seek, raw_output, normalized_records) do
    %CrawlJob{}
    |> CrawlJob.changeset(%{
      kind: "crawl_and_ingest",
      status: "completed",
      seek: seek,
      prompt: prompt(attrs, seek),
      raw_input: raw_input(attrs, seek),
      raw_output: raw_output,
      normalized_records: normalized_records,
      requested_at: DateTime.utc_now(),
      completed_at: DateTime.utc_now()
    })
    |> Repo.insert()
  end

  defp append_ingest_event(attrs, job, normalized_records) do
    Events.append_event(%{
      kind: "crawl_ingested",
      canon: map_value(attrs, "canon") || "operator",
      source: "local_ai_webapp_stack",
      payload: %{
        "crawl_job_id" => job.id,
        "schema_version" => @schema_version,
        "seek" => job.seek,
        "prompt_hash" => Hashing.sha256(job.prompt),
        "raw_output_hash" => Hashing.sha256(job.raw_output),
        "record_count" => normalized_records["count"],
        "normalized_records" => normalized_records
      },
      author: map_value(attrs, "author") || "codex"
    })
  end

  defp set_event(job, event) do
    job
    |> CrawlJob.changeset(%{
      kind: job.kind,
      status: job.status,
      seek: job.seek,
      prompt: job.prompt,
      raw_input: job.raw_input,
      raw_output: job.raw_output,
      normalized_records: job.normalized_records,
      requested_at: job.requested_at,
      completed_at: job.completed_at,
      event_id: event.id
    })
    |> Repo.update()
  end

  defp normalize_records(attrs, raw_output) do
    records =
      map_value(attrs, "records") ||
        map_value(attrs, "items") ||
        map_value(raw_output, "records") ||
        map_value(raw_output, "items")

    case normalize_record_list(records) do
      {:ok, normalized} ->
        {:ok,
         %{
           "schema_version" => @schema_version,
           "count" => length(normalized),
           "records" => normalized
         }}

      {:error, _reason} = error ->
        error
    end
  end

  defp normalize_record_list(records) when is_list(records) do
    records
    |> Enum.reduce_while({:ok, []}, fn record, {:ok, acc} ->
      case normalize_record(record) do
        {:ok, normalized} -> {:cont, {:ok, [normalized | acc]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, normalized} -> {:ok, Enum.reverse(normalized)}
      {:error, reason} -> {:error, reason}
    end
  end

  defp normalize_record_list(record) when is_map(record) do
    with {:ok, normalized} <- normalize_record(record), do: {:ok, [normalized]}
  end

  defp normalize_record_list(_records), do: {:error, :records_required}

  defp normalize_record(record) when is_map(record) and map_size(record) > 0 do
    normalized =
      record
      |> stringify_keys()
      |> Map.put_new("record_id", Ecto.UUID.generate())

    {:ok, normalized}
  end

  defp normalize_record(_record), do: {:error, :invalid_record}

  defp prompt(attrs, seek) do
    map_value(attrs, "prompt") || prompt_from_seek(seek)
  end

  defp prompt_from_seek(seek) when map_size(seek) == 0 do
    """
    Create a local crawl plan and return JSON with a records array. Use public sources only.
    """
    |> String.trim()
  end

  defp prompt_from_seek(seek) do
    """
    Create a local crawl plan for this seek object and return JSON matching the provided schema.
    Use public sources only. Persist raw findings separately from normalized records.

    #{Jason.encode!(seek)}
    """
    |> String.trim()
  end

  defp raw_input(attrs, seek) do
    %{
      "schema_version" => @schema_version,
      "seek" => seek,
      "requested_by" => map_value(attrs, "author") || "operator"
    }
  end

  defp maybe_filter_status(query, nil), do: query
  defp maybe_filter_status(query, ""), do: query

  defp maybe_filter_status(query, status) do
    where(query, [job], job.status == ^status)
  end

  defp maybe_limit(query, nil), do: query

  defp maybe_limit(query, limit) when is_integer(limit) and limit > 0 do
    limit(query, ^limit)
  end

  defp maybe_limit(query, _limit), do: query

  defp stringify_keys(map) do
    Map.new(map, fn
      {key, value} when is_atom(key) -> {Atom.to_string(key), value}
      {key, value} when is_binary(key) -> {key, value}
      {key, value} -> {to_string(key), value}
    end)
  end

  defp map_value(map, key) when is_map(map) and is_binary(key) do
    Map.get(map, key) || Map.get(map, String.to_existing_atom(key))
  rescue
    ArgumentError -> Map.get(map, key)
  end
end
